---
title: "R Notebook"
output: html_notebook
---

```{r}
library(bnlearn)
dag <- empty.graph(nodes = c("A", "S", "E", "O", "R", "T"))
arc.set <-matrix(c("A", "E",
                   "S", "E",
                   "E", "O",
                   "E", "R",
                   "O", "T",
                   "R", "T"),
                 byrow = TRUE, ncol = 2,
                 dimnames = list(NULL, c("from", "to")))
arcs(dag) <- arc.set
nodes(dag)
```

```{r}
arcs(dag)
```

```{r}
graphviz.plot(dag)
```
```{r}
A.lv <- c("young", "adult", "old")
S.lv <- c("M", "F")
E.lv <- c("high", "uni")
O.lv <- c("emp", "self")
R.lv <- c("small", "big")
T.lv <- c("car", "train", "other")

A.prob <- array(c(0.3,0.5,0.2), dim = 3, dimnames = list(A = A.lv))
S.prob <- array(c(0.6,0.4), dim = 2, dimnames = list(S = S.lv))
E.prob <- array(c(0.75,0.25,0.72,0.28,0.88,0.12,0.64,0.36,0.70,0.30,0.90,0.10), dim = c(2,3,2), dimnames = list(E = E.lv, A = A.lv, S = S.lv))
O.prob <- array(c(0.96,0.04,0.92,0.08), dim = c(2,2), dimnames = list(O = O.lv, E = E.lv))
R.prob <- array(c(0.25,0.75,0.2,0.8), dim = c(2,2), dimnames = list(R = R.lv, E = E.lv))
T.prob <- array(c(0.48,0.42,0.10,0.56,0.36,0.08,0.58,0.24,0.18,0.70,0.21,0.09), dim = c(3,2,2), dimnames = list(T = T.lv, O = O.lv, R = R.lv))
cpt <- list(A = A.prob, S = S.prob, E = E.prob, O = O.prob, R = R.prob, T = T.prob)

```

```{r}
cpt
```
```{r}
# fit cpt table to network
bn <- custom.fit(dag, cpt)
```
```{r}
survey <- read.table("data/survey.txt", header = TRUE)
head(survey)
```
```{r}
bn.mle <- bn.fit(dag, data = survey, method = "mle")
bn.mle
```
```{r}
bn.bayes <- bn.fit(dag, data = survey, method = "bayes", iss = 10)
bn.bayes
```
```{r}
data(gaussian.test)
dag2 = model2network("[A][B][E][G][C|A:B][D|B][F|A:D:E:G]")
graphviz.plot(dag2)
```


```{r}
model <- bn.fit(dag2, data = gaussian.test[1:2000,])
```

```{r}
test <- gaussian.test[2001:nrow(gaussian.test), ]
predicted <- predict(
    model,
    node = "A",
    data = test,
    method = "bayes-lw")

plot(test$A, predicted, xlab = "actual", ylab = "predicted")
```



